---
title: "Field Report test"
date: today
format:
  html:
    embed-resources: true
    number_sections: true
    toc: true 
format-links: false
execute:
  echo: false
  warning: false
params:
  individual_collector: "JMP"
  SiteVisitID: current_SiteVisitID
  RunCode: current_RunCode
  RunDate: current_RunDate
  SiteCode: current_SiteCode
---

Collector: **`r params$individual_collector`**

```{r setup, include = FALSE}
library(readr)
library(here)
library(dplyr)
library(ggplot2)
library(stringr)
library(purrr)
library(htmltools)
library(knitr)
library(gt)
library(kableExtra)
library(tidyr)

data2018 <- readRDS("data/PINCommEngData (2).RData")

data2018 <-  data2018 %>%
  mutate(RunDate = format(as.Date(RunDate), "%m-%d-%Y")) 
```

```{r}
#| results: hide

data2018_primary <- data2018 %>%
  mutate(Collectors = str_sub(Collectors, start = 1, end = 3))

data2018_subset <- data2018_primary %>% filter(str_detect(Collectors, fixed(params$individual_collector)))

data2018_subset <- data2018_subset %>%
  arrange(SiteVisitID)

SiteVisitID <- data2018_subset %>% 
  filter(str_detect(Collectors, fixed(params$individual_collector))) |> 
  distinct(SiteVisitID) %>% 
  pull()

RunDate <- data2018_subset %>% 
  filter(str_detect(Collectors, fixed(params$individual_collector))) |> 
  distinct(RunDate) %>% 
  pull()

RunCode <- data2018_subset %>%
  filter(str_detect(Collectors, fixed(params$individual_collector))) |> 
  distinct(RunCode) %>% 
  pull()

SiteCode <- data2018_subset %>%
  filter(str_detect(Collectors, fixed(params$individual_collector))) |> 
  distinct(SiteCode) %>% 
  pull()

```

# Quality Control Flags

The samples below have been flagged by the quality control perimeters.

```{r echo = FALSE}
data2018_subset %>% 
  filter(CollMethod == "CO-E",
         SampleDepth == 0) %>% 
  select(RunDate, RunCode, SiteCode, CollMethod, SampleDepth) %>% 
  gt() %>% 
  tab_header(title = "CO-E Quality Control Flags") %>% 
  tab_style(
    style = cell_borders(
      sides = c("all"),
      color = "black",
      weight = px(1),
      style = "solid"),
    locations = list(cells_body(), cells_column_labels()))
```

```{r}
data2018_subset %>% 
  filter(CollMethod == "GS", 
         SampleDepth != 0) %>% 
  select(RunDate, RunCode, SiteCode, CollMethod, SampleDepth) %>% 
  gt() %>% 
  tab_header(title = "GS Quality Control Flags") %>% 
  tab_style(
    style = cell_borders(
      sides = c("all"),
      color = "black",
      weight = px(1),
      style = "solid"),
    locations = list(cells_body(), cells_column_labels()))
```

```{r}
#| output: asis


SiteVisitID_Sections <- map_chr(SiteVisitID, \(current_SiteVisitID) {

current_RunDate <- data2018_subset[data2018_subset$SiteVisitID == current_SiteVisitID, "RunDate"] %>%
distinct() %>% pull()
current_RunCode <- data2018_subset[data2018_subset$SiteVisitID == current_SiteVisitID, "RunCode"] %>%
distinct %>% pull()
current_SiteCode <- data2018_subset[data2018_subset$SiteVisitID == current_SiteVisitID, "SiteCode"] %>% distinct %>% pull()

{
params <- (RunDate = current_RunDate)
params <- (RunCode = current_RunCode)
params <- (SiteCode = current_SiteCode)
knitr::knit_child(
input = "child_Template_Ludwin.qmd",
envir = rlang::env(),
quiet = TRUE
)
}
})


cat(SiteVisitID_Sections, sep = "\n")

```

```{r load-packages-and-data, echo = FALSE, message = FALSE, warning = FALSE}
# library(tidyverse)
# library(data.table)
# library(gt)
# library(purrr)
# library(quarto)
# library(here)
# library(knitr)
# library(rlang)
# library(kableExtra)
# library(tibble)
# library(rmarkdown)
# 
# data2018 <- readRDS("data/PINCommEngData (2).RData")
# 
# data <- filter(data2018, Collectors == params$Collectors)
```

```{r echo = FALSE, message = FALSE, warning = FALSE}
# collectors <- data %>%
#   filter(Collectors == params$Collectors) %>%
#   distinct(Collectors) %>%
#   pull()
# 
# rundate <- data %>%
#   filter(RunDate == RunDate) %>%
#   select(RunDate) %>%
#   mutate(RunDate = as.character(RunDate)) %>%
#   pull()
# 
# runcode <- data %>%
#   filter(RunCode == RunCode) %>%
#   select(RunCode) %>%
#   pull()
# 
# sitecode <- data %>%
#   filter(SiteCode == SiteCode) %>%
#   select(SiteCode) %>%
#   pull()
```

```{r echo = FALSE, message = FALSE, warning = FALSE}
#| output: asis

# RunDate <- map_chr(data, \(current_RunDate){
#   knit_child(
#     input = "samples_child_doc.qmd",
#     envir = env(),
#     quiet = TRUE
#     )
# })
# 
# print(RunDate, sep = "\n")
```
