# Date: `r RunDate`, RunCode: `r RunCode`, SiteCode: `r SiteCode`

::: panel-tabset
### Site Info

```{r}
data2018 %>% 
  filter(SiteVisitID == current_SiteVisitID) %>% 
   select(RunCode, WaterBody, SiteCode, SiteVisitStartTime, SiteDepth) %>%
  rename("Water Body" = "WaterBody",
         "Site" = "SiteCode",
         "Run Code" = "RunCode",
         "Time" = "SiteVisitStartTime",
         "Depth" = "SiteDepth") %>%
  distinct() %>% 
  gt() %>%
  cols_align(align = "center") %>% 
  tab_header(title = "Site information") %>%
  tab_style(
    style = cell_borders(
      sides = c("all"),
      color = "black",
      weight = px(1),
      style = "solid"),
    locations = list(cells_body(), cells_column_labels()))
```

```{r}
data2018 %>% 
  filter(SiteVisitID == current_SiteVisitID) %>% 
  select(Weather, SamplingAirTemp, RivCond, WaterLevel, FoamRank, FoamSource) %>% 
  rename("Air Temp" = "SamplingAirTemp",
         "River Cond" = "RivCond", 
         "Water Level" = "WaterLevel",
         "Foam Rank" = "FoamRank",
         "Foam Source" = "FoamSource") %>%
  distinct() %>% 
  gt() %>%
  cols_align(align = "center") %>%
  tab_header(title = "Abiotic Factors") %>%
  tab_style(
    style = cell_borders(
      sides = c("all"),
      color = "black",
      weight = px(1),
      style = "solid"),
    locations = list(cells_body(), cells_column_labels()))
```

```{r}
data2018 %>% 
  filter(SiteVisitID == current_SiteVisitID) %>% 
  select(SiteVisitComment) %>% 
  rename("Site Visit Notes" = "SiteVisitComment") %>%
  distinct() %>% 
  gt() %>%
  cols_align(align = "center") %>%
  tab_style(
    style = cell_borders(
      sides = c("all"),
      color = "black",
      weight = px(1),
      style = "solid"),
    locations = list(cells_body(), cells_column_labels()))
```

### Samples

```{r}
data2018 %>% 
  filter(SiteVisitID == current_SiteVisitID) %>% 
  select(SampleName, ProjectCode, CntrType, QCType, CollMethod, SampleDepth, LabAbbrev) %>%
  rename("Sample Name" = "SampleName", 
         "Project" = "ProjectCode", 
         "Container" = "CntrType", 
         "QC" = "QCType",
         "Method" = "CollMethod",
         "Depth" = "SampleDepth") %>%
  group_by(LabAbbrev) %>%
  distinct() %>% 
  gt() %>%
tab_style(
    style = cell_fill(color = "lightgreen"),
    locations = cells_body(columns = c(Depth),
                           rows = Method == "GS" & Depth == 0)) %>%
  tab_style(
    style = cell_fill(color = "red"),
    locations = cells_body(columns = c(Depth),
                           rows = Method == "CO-E" & Depth == 0)) %>%
  tab_style(
    style = cell_fill(color = "red"),
    locations = cells_body(columns = c(Depth),
                           rows = Method == "GS" & Depth != 0)) %>%
  cols_align(align = "center") %>%
  tab_style(
    style = cell_borders(
      sides = c("all"),
      color = "black",
      weight = px(1),
      style = "solid"),
    locations = list(cells_body(), cells_column_labels()))
```

### DO & Temperature

```{r}

data2018$SampleDatetime <- as.POSIXct(data2018$SampleDatetime, format = "%m/%d/%Y %H:%M:%S")

data2018$Date <- as.Date(data2018$SampleDatetime)
data2018$Time <- format(data2018$SampleDatetime, format = "%H:%M:%S")


data2018 %>% 
  select(QCType, ProfileDepth,Const, Result, SiteVisitID) %>% 
  filter(Const %in% c("Dissolved Oxygen", "water temperature")) %>% 
  pivot_wider(names_from = c(Const, QCType),
              values_from = Result,
              values_fn = list(Result = list)) %>%  # Keep all values
  rename("Water Temperature Regular" = "water temperature_Regular",
         "Water Temperature Duplicate" = "water temperature_Duplicate",
         "DO Regular" = "Dissolved Oxygen_Regular",
         "DO Duplicate" = "Dissolved Oxygen_Duplicate") %>%
  mutate(across(ends_with("_regular"), ~replace_na(as.character(.), "-")),
         across(ends_with("_duplicate"), ~replace_na(as.character(.), "-"))) %>% 
  filter(SiteVisitID == current_SiteVisitID) %>% 
  select(!SiteVisitID) %>% 
  gt() %>% 
      opt_row_striping() %>%
  tab_style(
    style = cell_borders(
      sides = c("all"),
      color = "black",
      weight = px(1),
      style = "solid"),
    locations = list(cells_body(), cells_column_labels()))


```

```{r}
data2018 %>%
  select(Const, Result, QCType, Time, SiteVisitID ) %>% 
  filter(Const %in% c("Secchi","pH")) %>% 
  pivot_wider(names_from = c(Const, QCType),
              values_from = Result,
              values_fn = list(Result = list)) %>%  # Keep all values
  mutate(across(ends_with("_Duplicate"), ~replace_na(as.character(.), "-")),
         across(ends_with("_Regular"), ~replace_na(as.character(.), "-"))) %>% 
  filter(SiteVisitID == current_SiteVisitID) %>% 
  select(!SiteVisitID) %>% 
  rename_with(~str_replace_all(., "_", " "), matches("_Regular$|_Duplicate$")) %>%
  gt() %>% 
  cols_move(
    columns = "pH Duplicate",
    after = "pH Regular"
  ) %>% 
  opt_row_striping() %>%
  tab_style(
    style = cell_borders(
      sides = c("all"),
      color = "black",
      weight = px(1),
      style = "solid"),
    locations = list(cells_body(), cells_column_labels()))
```

```{r}
data2018 %>% 
  filter(SiteVisitID == "JanS7-201871875659") %>% 
  select(FilterName) %>%
  rename("Filter Name" = "FilterName") %>%
  distinct() %>%
  gt() %>%
  cols_align(align = "center") %>%
  tab_style(
    style = cell_borders(
      sides = c("all"),
      color = "black",
      weight = px(1),
      style = "solid"),
    locations = list(cells_body(), cells_column_labels()))
```
:::


