---
title: "Water Quality Field Report Template"
format: html
editor: visual
execute:
  echo: false
  warning: false
---

```{r install.packages, include=FALSE}
library(tidyverse)
library(quarto)
library(dplyr)
library(devtools)
library(readr)
library(gt) #for tables
library(stringr)
library(htmltools)
```

```{r load_data}
data2018 <- readRDS("data/PINCommEngData (2).RData")
```

## Controls Summary

### Collector: JRP

Run Date: **2018-09-19** Run: **Passadumkeag**

------------------------------------------------------------------------

::: panel-tabset
## Collection Information

```{r}

data2018 %>% 
  filter(SiteVisitID == "JanS5-2018925102747") %>% 
  select(RunCode, WaterBody, SiteCode, SiteVisitStartTime, SiteDepth) %>%
  rename("Water Body" = "WaterBody",
         "Site" = "SiteCode",
         "Run Code" = "RunCode",
         "Time" = "SiteVisitStartTime",
         "Depth" = "SiteDepth") %>%
  distinct() %>% 
  gt() %>%
  cols_align(align = "center") %>% 
  tab_header(title = "Site information") %>%
  tab_style(
    style = cell_borders(
      sides = c("all"),
      color = "black",
      weight = px(1),
      style = "solid"),
    locations = list(cells_body(), cells_column_labels()))

data2018 %>% 
  filter(SiteVisitID == "JanS5-2018925102747") %>% 
  select(Weather, SamplingAirTemp, RivCond, WaterLevel, FoamRank, FoamSource) %>% 
  rename("Air Temp" = "SamplingAirTemp",
         "River Cond" = "RivCond", 
         "Water Level" = "WaterLevel",
         "Foam Rank" = "FoamRank",
         "Foam Source" = "FoamSource") %>%
  distinct() %>% 
  gt() %>%
  cols_align(align = "center") %>%
  tab_header(title = "Abiotic Factors") %>%
  tab_style(
    style = cell_borders(
      sides = c("all"),
      color = "black",
      weight = px(1),
      style = "solid"),
    locations = list(cells_body(), cells_column_labels()))

data2018 %>% 
  filter(SiteVisitID == "JanS5-2018925102747") %>% 
  select(SiteVisitComment) %>% 
  rename("Site Visit Notes" = "SiteVisitComment") %>%
  distinct() %>% 
  gt() %>%
  cols_align(align = "center") %>%
  tab_style(
    style = cell_borders(
      sides = c("all"),
      color = "black",
      weight = px(1),
      style = "solid"),
    locations = list(cells_body(), cells_column_labels()))


```

## Samples

```{r}

data2018 %>% 
  filter(SiteVisitID == "JanS7-201871875659", CntrType != "Msmt") %>% 
  select(SampleName, ProjectCode, CntrType, QCType, CollMethod, SampleDepth, LabAbbrev) %>%
  rename("Sample Name" = "SampleName", 
         "Project" = "ProjectCode", 
         "Container" = "CntrType", 
         "QC" = "QCType",
         "Method" = "CollMethod",
         "Depth" = "SampleDepth") %>%
  group_by(LabAbbrev) %>%
  distinct() %>% 
  gt() %>%
tab_style(
    style = cell_fill(color = "lightgreen"),
    locations = cells_body(columns = c(Depth),
                           rows = Method == "GS" & Depth == 0)) %>%
  tab_style(
    style = cell_fill(color = "red"),
    locations = cells_body(columns = c(Depth),
                           rows = Method == "CO-E" & Depth == 0)) %>%
  tab_style(
    style = cell_fill(color = "red"),
    locations = cells_body(columns = c(Depth),
                           rows = Method == "GS" & Depth != 0)) %>%
  cols_align(align = "center") %>%
  tab_style(
    style = cell_borders(
      sides = c("all"),
      color = "black",
      weight = px(1),
      style = "solid"),
    locations = list(cells_body(), cells_column_labels()))
```

## DO and Temperature

```{r}

data2018$SampleDatetime <- as.POSIXct(data2018$SampleDatetime, format = "%m/%d/%Y %H:%M:%S")

data2018$Date <- as.Date(data2018$SampleDatetime)
data2018$Time <- format(data2018$SampleDatetime, format = "%H:%M:%S")


data2018 %>% 
  select(QCType, ProfileDepth,Const, Result, SiteVisitID) %>% 
  filter(Const %in% c("Dissolved Oxygen", "water temperature")) %>% 
  pivot_wider(names_from = c(Const, QCType),
              values_from = Result) %>%
  rename("water_temp_regular" = "water temperature_Regular",
         "water_temp_duplicate" = "water temperature_Duplicate",
         "DO_regular" = "Dissolved Oxygen_Regular",
         "DO_duplicate" = "Dissolved Oxygen_Duplicate") %>%
  mutate(water_temp_regular = as.character(water_temp_regular),
     water_temp_regular = replace_na(water_temp_regular, "-"),
  water_temp_duplicate = as.character(water_temp_duplicate),
    water_temp_duplicate = replace_na(water_temp_duplicate, "-"),
     DO_regular = as.character(DO_regular),
    DO_regular = replace_na(DO_regular, "-"),
        DO_duplicate = as.character(DO_duplicate),
    DO_duplicate = replace_na("DO_duplicate", "-")) %>%
    filter(SiteVisitID == "JanS7-201871875659") %>%
    select(!SiteVisitID) %>% 
  gt() %>% 
      opt_row_striping() %>%
  tab_style(
    style = cell_borders(
      sides = c("all"),
      color = "black",
      weight = px(1),
      style = "solid"),
    locations = list(cells_body(), cells_column_labels()))


  

data2018 %>% 
    # filter(Collector == "JRP", RunCode == "Passadumkeag", RunDate == "2018-07-18") %>%
  select(Const, Result, QCType, Time, SiteVisitID ) %>% 
  filter(Const %in% c("Secchi","pH")) %>% 
  pivot_wider(names_from = c(Const, QCType),
              values_from = Result) %>%
  mutate(pH_Duplicate = as.character(pH_Duplicate),
    pH_Duplicate = replace_na(pH_Duplicate, "-"),
    Secchi_Duplicate = as.character(Secchi_Duplicate),
    Secchi_Duplicate = replace_na(Secchi_Duplicate, "-"),
     Secchi_Regular = as.character(Secchi_Regular),
    Secchi_Regular = replace_na(Secchi_Regular, "-"),
        pH_Regular = as.character(pH_Regular),
    pH_Regular = replace_na(pH_Regular, "-")) %>% 
    filter(SiteVisitID == "JanS7-201871875659") %>%
    select(!SiteVisitID) %>% 
   rename("pH Regular" = "pH_Regular",
          "pH Duplicate" = "pH_Duplicate",
          "Secchi Regular" = "Secchi_Regular",
          "Secchi Duplicate" = "Secchi_Duplicate") %>%
  gt() %>% 
    cols_move(
    columns = "pH Duplicate",
    after = "pH Regular"
  ) %>% 
      opt_row_striping() %>%
  tab_style(
    style = cell_borders(
      sides = c("all"),
      color = "black",
      weight = px(1),
      style = "solid"),
    locations = list(cells_body(), cells_column_labels()))


data2018 %>% 
  filter(SiteVisitID == "JanS7-201871875659") %>% 
  select(FilterName) %>%
  rename("Filter Name" = "FilterName") %>%
  distinct() %>%
  gt() %>%
  cols_align(align = "center") %>%
  tab_style(
    style = cell_borders(
      sides = c("all"),
      color = "black",
      weight = px(1),
      style = "solid"),
    locations = list(cells_body(), cells_column_labels()))

```
:::
