### `r paste("Collector", which(collectors == current_collectors), ":", current_collectors)`

::: panel-tabset
## Collection Information

```{r}
data2018 %>% 
  filter(Collectors == current_collector) %>% 
  select(RunCode ,WaterBody, SiteCode, SiteVisitStartTime, SiteDepth) %>%
  rename("Water Body" = "WaterBody",
         "Site" = "SiteCode",
         "Run Code" = "RunCode",
         "Time" = "SiteVisitStartTime",
         "Depth" = "SiteDepth") %>%
  distinct() %>% 
  gt() %>%
  cols_align(align = "center") %>% 
  tab_header(title = "Site information")

data2018 %>% 
  filter(Collectors == current_collector) %>%
  select(Weather, SamplingAirTemp, RivCond, WaterLevel, FoamRank, FoamSource, SiteVisitComment) %>% 
  rename("Air Temp" = "SamplingAirTemp",
         "River Cond" = "RivCond", 
         "Water Level" = "WaterLevel",
         "Foam Rank" = "FoamRank",
         "Foam Source" = "FoamSource") %>%
  distinct() %>% 
  gt() %>%
  cols_align(align = "center") %>%
  tab_header(title = "Abiotic Factors")

data2018 %>% 
  filter(Collectors == current_collector) %>%
  select(SiteVisitComment) %>% 
  rename("Site Visit Notes" = "SiteVisitComment") %>%
  distinct() %>% 
  gt() %>%
  cols_align(align = "center")


```

## Samples

```{r}

data2018 %>% 
  filter(Collectors == current_collector) %>% 
  select(SampleName, ProjectCode, CntrType, QCType, CollMethod, SampleDepth, LabAbbrev) %>% 
  group_by(LabAbbrev) %>% 
  distinct() %>% 
  gt() %>%
tab_style(
    style = cell_fill(color = "lightgreen"),
    locations = cells_body(columns = c(SampleDepth),
                           rows = CollMethod == "GS" & SampleDepth == 0)) %>%
  tab_style(
    style = cell_fill(color = "red"),
    locations = cells_body(columns = c(SampleDepth),
                           rows = CollMethod == "CO-E" & SampleDepth == 0)) %>%
  tab_style(
    style = cell_fill(color = "red"),
    locations = cells_body(columns = c(SampleDepth),
                           rows = CollMethod == "GS" & SampleDepth != 0)) %>%
  cols_align(align = "center")
```

## DO and Temperature

```{r}

data2018$SampleDatetime <- as.POSIXct(data2018$SampleDatetime, format = "%m/%d/%Y %H:%M:%S")

data2018$Date <- as.Date(data2018$SampleDatetime)
data2018$Time <- format(data2018$SampleDatetime, format = "%H:%M:%S")



data2018 %>%
  filter(Collectors == current_collector) %>%
  filter(Const %in% c("Dissolved Oxygen", "water temperature"),
         SiteDepthMethod == "Secchi disk") %>% 
  select(QCType, ProfileDepth,Const, Result) %>%
  na.omit() %>%
  pivot_wider(names_from = "Const", values_from = "Result") %>%
  gt() %>% 
    opt_row_striping()

data2018 %>% 
  filter(Collectors == current_collector) %>%
  select(Const, Result, QCType, Date, Time, SiteVisitID ) %>% 
  filter(Const %in% c("Secchi","pH")) %>% 
  pivot_wider(names_from = c(Const, QCType),
              values_from = Result) %>%
  mutate(pH_Duplicate = as.character(pH_Duplicate),
    pH_Duplicate = replace_na(pH_Duplicate, "-"),
    Secchi_Duplicate = as.character(Secchi_Duplicate),
    Secchi_Duplicate = replace_na(Secchi_Duplicate, "-"),
     Secchi_Regular = as.character(Secchi_Regular),
    Secchi_Regular = replace_na(Secchi_Regular, "-"),
        pH_Regular = as.character(pH_Regular),
    pH_Regular = replace_na(pH_Regular, "-")) %>% 
    filter(SiteVisitID == "JanS7-201871875659") %>%
    select(!SiteVisitID) %>% 
  gt() %>% 
    cols_move(
    columns = "pH_Duplicate",
    after = "pH_Regular"
  ) %>% 
      opt_row_striping()


data2018 %>% 
  filter(Collectors == current_collector) %>%
  select(FilterName) %>% 
  distinct() %>%
  gt() %>%
  cols_align(align = "center")

```
:::