---
title: "Water Quality Lab Report Template"
format: html
editor: visual
execute:
  echo: false
  warning: false
---

```{r install.packages, include=FALSE}
library(tidyverse)
library(quarto)
library(dplyr)
library(devtools)
library(readr)
library(gt) #for tables
library(stringr)
library(htmltools)
library(lubridate)
```

```{r load_data}
data2018 <- readRDS("data/PINCommEngData (2).RData")
```

## Lab Report Header {.smaller}

### Collector: JRP

Run Date: **2018-09-19** Run: **Passadumkeag**

```{r}

data2018$SampleDatetime <- (as.POSIXct(data2018$SampleDatetime, format = "%m/%d/%Y %H:%M:%S"))
data2018$LabAnalysisDatetime <- (as.POSIXct(data2018$LabAnalysisDatetime, format = "%m/%d/%Y %H:%M:%S"))

#HoldTimeMins <- data2018 %>%
#  mutate(HoldTimeMins = as.double(difftime(LabAnalysisDatetime, SampleDatetime, units #= "mins"), na.rm = TRUE))

  
data2018 %>%
  separate_longer_delim(cols = Constituents, delim = ";") %>%
  filter(SiteVisitID == "JanS5-2018925102747") %>%
  mutate(HoldTimeMins = as.numeric(lubridate::ymd_hms(LabAnalysisDatetime) - lubridate::ymd_hms(SampleDatetime))*60*24) %>%
   mutate(HoldTime = seconds_to_period(as.numeric(HoldTimeMins)*60)) %>%
   mutate(HoldTimeViol = case_when(Constituents == "Cond" ~ HoldTimeMins - 40320,
                                  Constituents == "Turb" ~ HoldTimeMins - 1440,
                                  Constituents == "ColA" ~ HoldTimeMins - 2880,
                                  Constituents == "TSS" ~ HoldTimeMins - 10080,
                                  Constituents == "EcoliIQT" ~ HoldTimeMins - 360,
                                  Constituents == "BOD" ~ HoldTimeMins - 360,
                                  Constituents == "TotP" ~ HoldTimeMins - 40320,
                                  Constituents == "Alk" ~ HoldTimeMins - 20160,
                                  Constituents == "ColT" ~ HoldTimeMins - 2880,
                                  Constituents == "ColiformIQT" ~ HoldTimeMins - 360,
                                  TRUE ~ NA
                                  )) %>%
  select(SiteCode, SampleDatetime, ResultValue, QCType, Constituents, ResultFlag_ID, IncubationLength, LabAnalysisDatetime, HoldTime, HoldTimeViol) %>%
  distinct() %>% 
  rename("QC Type" = "QCType",
         "Qualifier Flag" = "ResultFlag_ID",
         "Incubation Time" = "IncubationLength",
         "Analysis Time" = "LabAnalysisDatetime",
         "Hold Time" = "HoldTime",
         "Site Code" = "SiteCode",
         "Sample Date/Time" = "SampleDatetime",
         "Result" = "ResultValue") %>%
  gt() %>%
  tab_style(
    style = cell_fill(color = "lightgreen"),
    locations = cells_body(columns = c(HoldTimeViol),
                           rows = grepl("-", HoldTimeViol, fixed=TRUE))) %>%
  tab_style(
    style = cell_fill(color = "red"),
    locations = cells_body(columns = c(HoldTimeViol),
                           rows = !grepl("-", HoldTimeViol, fixed=TRUE))) %>%
  cols_align(align = "center") %>%
   tab_style(
    style = cell_borders(
      sides = c("all"),
      color = "black",
      weight = px(1),
      style = "solid"),
    locations = list(cells_body(), cells_column_labels()))
```

```{r}
#c <- data2018 %>%
#  filter(Collector == "JRP", RunCode == "Passadumkeag", #RunDate == "2018-09-19")

#data2018 %>%
#  mutate(
 #   Constituents = case_when(
 #     Constituents == "Msmt" ~ Const,
#      TRUE ~ Constituents
#    ),
 #   ResultValue = coalesce(Result, ResultValue)) %>%
 # filter(Collector == "JRP", RunCode == "Passadumkeag", #RunDate == "2018-09-19") %>%
#  select(SiteCode, SiteVisitStartTime, Constituents, ResultValue, QCType, IncubationLength, LabAnalysisDatetime, SampleDatetime) %>%
 # gt()
```
