
```{r}
data2018 <- readRDS("data/PINCommEngData (2).RData")

data2018_primary <- data2018 %>%
  mutate(Collectors = str_sub(Collectors, start = 1, end = 3))

data2018_primary$SampleDatetime <- as.POSIXct(data2018_primary$SampleDatetime, format = "%m/%d/%Y %H:%M:%S")

data2018_primary$Date <- as.Date(data2018_primary$SampleDatetime)
data2018_primary$Time <- format(data2018_primary$SampleDatetime, format = "%H:%M:%S")
```

```{r 1}
data2018_primary %>% 
   select(RunCode, WaterBody, SiteCode, SiteVisitStartTime, SiteDepth) %>%
  rename("Water Body" = "WaterBody",
         "Site" = "SiteCode",
         "Run Code" = "RunCode",
         "Time" = "SiteVisitStartTime",
         "Depth" = "SiteDepth") %>%
  distinct() %>% 
  gt() %>%
  cols_align(align = "center") %>% 
  tab_header(title = "Site information") %>%
  tab_style(
    style = cell_borders(
      sides = c("all"),
      color = "black",
      weight = px(1),
      style = "solid"),
    locations = list(cells_body(), cells_column_labels()))
```

```{r 2}
data2018_primary %>% 
  select(Weather, SamplingAirTemp, RivCond, WaterLevel, FoamRank, FoamSource) %>% 
  rename("Air Temp" = "SamplingAirTemp",
         "River Cond" = "RivCond", 
         "Water Level" = "WaterLevel",
         "Foam Rank" = "FoamRank",
         "Foam Source" = "FoamSource") %>%
  distinct() %>% 
  gt() %>%
  cols_align(align = "center") %>%
  tab_header(title = "Abiotic Factors") %>%
  tab_style(
    style = cell_borders(
      sides = c("all"),
      color = "black",
      weight = px(1),
      style = "solid"),
    locations = list(cells_body(), cells_column_labels()))
```

```{r 3}
data2018_primary %>% 
  select(SiteVisitComment) %>% 
  rename("Site Visit Notes" = "SiteVisitComment") %>%
  distinct() %>% 
  gt() %>%
  cols_align(align = "center") %>%
  tab_style(
    style = cell_borders(
      sides = c("all"),
      color = "black",
      weight = px(1),
      style = "solid"),
    locations = list(cells_body(), cells_column_labels()))
```

```{r 4}
data2018_primary %>% 
  select(SampleName, ProjectCode, CntrType, QCType, CollMethod, SampleDepth, LabAbbrev) %>%
  rename("Sample Name" = "SampleName", 
         "Project" = "ProjectCode", 
         "Container" = "CntrType", 
         "QC" = "QCType",
         "Method" = "CollMethod",
         "Depth" = "SampleDepth") %>%
  group_by(LabAbbrev) %>%
  distinct() %>% 
  gt() %>%
tab_style(
    style = cell_fill(color = "#B3E0A6"),
    locations = cells_body(columns = c(Depth),
                           rows = Method == "GS" & Depth == 0)) %>%
  tab_style(
    style = cell_fill(color = "#F5725E"),
    locations = cells_body(columns = c(Depth),
                           rows = Method == "CO-E" & Depth == 0)) %>%
  tab_style(
    style = cell_fill(color = "#F5725E"),
    locations = cells_body(columns = c(Depth),
                           rows = Method == "GS" & Depth != 0)) %>%
  cols_align(align = "center") %>%
  opt_interactive(use_sorting = TRUE, use_filters = TRUE, use_page_size_select = TRUE, page_size_default = 5, page_size_values = c(5, 10, 25, 50, 100)) %>%
   tab_style(
    style = cell_borders(
      sides = c("all"),
      color = "black",
      weight = px(1),
      style = "solid"),
     locations = list(cells_body()))
```

```{r 6}
data2018_primary %>% 
  select(FilterName) %>%
  filter(FilterName != "NA") %>% 
  rename("Filter Name" = "FilterName") %>%
  distinct() %>%
  gt() %>%
  cols_align(align = "center") %>%
  tab_style(
    style = cell_borders(
      sides = c("all"),
      color = "black",
      weight = px(1),
      style = "solid"),
    locations = list(cells_body(), cells_column_labels()))
```

```{r}
data2018_primary %>%
  select(QCType, ProfileDepth, Const, Result, SiteVisitID) %>%
  filter(Const %in% c("Dissolved Oxygen", "water temperature")) %>%
  pivot_wider(names_from = c(Const, QCType),
              values_from = Result) %>%
  mutate(across(ends_with("_regular"), ~replace_na(as.character(.), "-")),
         across(ends_with("_duplicate"), ~replace_na(as.character(.), "-"))) %>%
  rename("Water Temperature Regular" = "water temperature_Regular",
         "Water Temperature Duplicate" = "water temperature_Duplicate",
         "DO Regular" = "Dissolved Oxygen_Regular",
         "DO Duplicate" = "Dissolved Oxygen_Duplicate") %>%
  select(ProfileDepth, "Water Temperature Regular", "Water Temperature Duplicate", "DO Regular", "DO Duplicate") %>%
  gt() %>%
      opt_row_striping() %>%
  opt_interactive(use_sorting = TRUE, use_filters = TRUE, use_page_size_select = TRUE, page_size_default = 10, page_size_values = c(10, 25, 50, 100)) %>%
   tab_style(
    style = cell_borders(
      sides = c("all"),
      color = "black",
      weight = px(1),
      style = "solid"),
     locations = list(cells_body()))

output1 <- data2018_primary %>%
  select(QCType, ProfileDepth, Const, Result, SiteVisitID) %>%
  filter(Const %in% c("Dissolved Oxygen", "water temperature")) %>%
  pivot_wider(names_from = c(Const, QCType),
              values_from = Result) %>%
  mutate(across(ends_with("_regular"), ~replace_na(as.character(.), "-")),
        across(ends_with("_duplicate"), ~replace_na(as.character(.), "-"))) %>%
  rename("Water Temperature Regular" = "water temperature_Regular",
         "Water Temperature Duplicate" = "water temperature_Duplicate",
         "DO Regular" = "Dissolved Oxygen_Regular",
         "DO Duplicate" = "Dissolved Oxygen_Duplicate") %>%
  select(ProfileDepth, "Water Temperature Regular", "Water Temperature Duplicate", "DO Regular", "DO Duplicate") %>% 
  as.vector()

output2 <- data2018_primary %>%
  select(QCType, ProfileDepth, Const, Result, SiteVisitID) %>%
  filter(Const %in% c("Dissolved Oxygen", "water temperature")) %>%
  pivot_wider(names_from = c(Const, QCType),
              values_from = Result) %>%
  mutate(across(ends_with("_regular"), ~replace_na(as.character(.), "-"))) %>%
  rename("Water Temperature Regular" = "water temperature_Regular",
         "DO Regular" = "Dissolved Oxygen_Regular") %>%
  select(ProfileDepth, "Water Temperature Regular", "DO Regular") %>% 
  as.vector()

duplicate <- all(c("Regular", "Duplicate") %in% data2018_primary$QCType) %>% 
  as.logical()

result <- data2018_primary %>%
  filter(Collectors == "",
         RunDate == "",
         RunCode == "",
         SiteCode == "") %>% 
  if_else(duplicate, output1, output2)

```

```{r}
data2018_primary %>%
  select(QCType, ProfileDepth, Const, Result, SiteVisitID) %>%
  filter(Const %in% c("Dissolved Oxygen", "water temperature")) %>%
  pivot_wider(names_from = c(Const, QCType),
              values_from = Result,
              values_fn = list(Result = list)) %>%
  mutate(across(ends_with("_regular"), ~replace_na(as.character(.), "-")),
         across(ends_with("_duplicate"), ~replace_na(as.character(.), "-"))) %>% 
  select(ProfileDepth, SiteVisitID, contains("_")) %>%
  rename_with(~ str_replace_all(., "_", " "), contains("_")) %>% 
  rename_with(~ str_to_title(., locale = "en"), contains(" ")) %>% 
  gt() %>%
  opt_row_striping() %>%
  opt_interactive(use_sorting = TRUE, use_filters = TRUE, use_page_size_select = TRUE, page_size_default = 10, page_size_values = c(10, 25, 50, 100)) %>%
   tab_style(
    style = cell_borders(
      sides = c("all"),
      color = "black",
      weight = px(1),
      style = "solid"),
     locations = list(cells_body()))
```

```{r}
data2018_primary %>% 
  select(Const, Result, QCType, Time, SiteVisitID ) %>% 
  filter(Const %in% c("Secchi","pH")) %>% 
  pivot_wider(names_from = c(Const, QCType),
              values_from = Result) %>%
  mutate(pH_Duplicate = as.character(pH_Duplicate),
    pH_Duplicate = replace_na(pH_Duplicate, "-"),
    Secchi_Duplicate = as.character(Secchi_Duplicate),
    Secchi_Duplicate = replace_na(Secchi_Duplicate, "-"),
     Secchi_Regular = as.character(Secchi_Regular),
    Secchi_Regular = replace_na(Secchi_Regular, "-"),
        pH_Regular = as.character(pH_Regular),
    pH_Regular = replace_na(pH_Regular, "-")) %>% 
    select(!SiteVisitID) %>% 
   rename("pH Regular" = "pH_Regular",
          "pH Duplicate" = "pH_Duplicate",
          "Secchi Regular" = "Secchi_Regular",
          "Secchi Duplicate" = "Secchi_Duplicate") %>%
  gt() %>% 
    cols_move(
    columns = "pH Duplicate",
    after = "pH Regular"
  ) %>% 
      opt_row_striping() %>%
  opt_interactive(use_sorting = TRUE, use_filters = TRUE, use_page_size_select = TRUE, page_size_default = 10, page_size_values = c(10, 25, 50, 100)) %>%
   tab_style(
    style = cell_borders(
      sides = c("all"),
      color = "black",
      weight = px(1),
      style = "solid"),
     locations = list(cells_body()))
```




