---
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r install_packages_libraries}
#install.packages("tidyverse")
#install.packages("dplyr")
#install.packages("devtools")
#install.packages("readr")
library(tidyverse)
library(dplyr)
library(devtools)
library(readr)
```

```{r read_data}
data2018 <- readRDS("~/Repos/Penobscot-Water/data/PINCommEngData (2).RData")

transport_temp <- read.table("~/Desktop/GitHub/Penobscot_Water/data/c_FieldTransportTemps.txt",
                             header = TRUE,
                             sep = ",")

containers <- read.table("~/Desktop/GitHub/Penobscot_Water/data/0_ContainerMgmt.txt",
                         header = TRUE,
                         sep = ",")
```

```{r}
trans_temp_2018 <- transport_temp %>% 
  mutate(Rundate = as.character(RunDate)) %>% 
  mutate(RunYear = str_sub(RunDate, start = 6, end = 9)) %>% 
  filter(RunYear == "2018")

data_transp <- data2018_primary %>% 
  mutate(RunDate = as.character(RunDate)) %>% 
  left_join(trans_temp_2018, by = join_by(RunCode == RunCode, RunDate == RunDate, SiteCode == SiteCode), keep = TRUE, relationship = "many-to-many") %>% 
  select(!RunDate.y, !RunCode.y, !SiteCode.y) %>% 
  rename(RunCode = RunCode.x,
         RunDate = RunDate.x, 
         SiteCode = SiteCode.x)

data_2018_all <- data_transp %>% 
  left_join(containers, by = join_by(CntrType == CntrType, CntrColor == CntrColor, CntrVol == CntrVol, SampleFilterMethod == SampleFilterMethod, ContainerCode == ContainerCode, ContainerAbbrev == ContainerAbbrev)) %>% 
  select(!RunDate.y, !RunCode.y, !SiteCode.y)
```


### Data Overview 
```{r glimpse_data}
# glimpse(data2018)
```

### Measured Runs
```{r count_runs_sampled}
 # data2018 %>% 
 #  count(RunCode)
```
