
```{r data}
# data2018 <- readRDS("data/PINCommEngData (2).RData")
# 
# data2018_primary <- data2018 %>%
#   mutate(Collectors = str_sub(Collectors, start = 1, end = 3))
# 
# data2018_primary$SampleDatetime <- as.POSIXct(data2018_primary$SampleDatetime, format = "%m/%d/%Y %H:%M:%S")
# 
# data2018_primary$Date <- as.Date(data2018_primary$SampleDatetime)
# data2018_primary$Time <- format(data2018_primary$SampleDatetime, format = "%H:%M:%S")
# 
# transport_temp <- read.table("data/c_FieldTransportTemps.txt",
#                              header = TRUE,
#                              sep = ",")
# 
# containers <- read.table("../../data/0_ContainerMgmt.txt",
#                          header = TRUE,
#                          sep = ",")

```

```{r transp-data}
transport_temp <- read.table("../../data/c_FieldTransportTemps.txt",
                             header = TRUE,
                             sep = ",") %>% 
  select(!c(OID, SiteCode, Sort1, Sort2, Sort3, TransportTemp_ID))

transport_temp <- transport_temp %>% 
  mutate(rundate = str_extract(RunDate, "\\d{0,2}[\\/]\\d{0,2}[\\/]\\d{2,4}")) %>% 
  mutate(RunDate = as_datetime(RunDate, format = "%m/%d/%Y %H:%M:%OS"))

transp_all <- data2018_primary %>% 
  full_join(transport_temp, join_by(RunDate == RunDate, RunCode == RunCode, Collectors == Staff, SampleName == SampleNames))

transp_all <- transp_all %>% 
  mutate(RunYear = str_sub(RunDate, start = 1, end = 4))

transp_all <- transp_all %>% 
  mutate(Constituent = str_split(Constituents, ";")) %>%
    unnest %>%
    mutate(Constituents = str_trim(Constituent))


```

```{r}
transp_all %>% 
        mutate(HoldTimeMins = as.numeric(difftime(LabAnalysisDatetime, SampleDatetime, units = "mins"))) %>%
        mutate(HoldTimeMins = round(HoldTimeMins)) %>% 
        mutate(HoldTime = minutes(HoldTimeMins)) %>%
        mutate(HoldTimeViol = case_when(
          Constituents == "Cond" ~ HoldTimeMins - 40320,
          Constituents == "Turb" ~ HoldTimeMins - 1440,
          Constituents == "ColA" ~ HoldTimeMins - 2880,
          Constituents == "TSS" ~ HoldTimeMins - 10080,
          Constituents == "EcoliIQT" ~ HoldTimeMins - 360,
          Constituents == "BOD" ~ HoldTimeMins - 360,
          Constituents == "TotP" ~ HoldTimeMins - 40320,
          Constituents == "Alk" ~ HoldTimeMins - 20160,
          Constituents == "ColT" ~ HoldTimeMins - 2880,
          Constituents == "ColiformIQT" ~ HoldTimeMins - 360,
          TRUE ~ NA_real_
        ))

guess_formats(transp_all$ProcessDateTime, "mdy_HMS")

transp_all <- transp_all %>% 
  mutate(ProcessDateTime = mdy_hms(ProcessDateTime)) %>% 
  mutate(AnalysisTimeMins = as.numeric(difftime(ProcessDateTime, LabAnalysisDatetime, units = "mins")))

transp_all <- transp_all %>% 
  mutate(AnalysisTimeMins = as_hms(AnalysisTimeMins))



```


